### ISSUE TITLE
Can't get broad work

### ISSUE THREAD

**Issue by anhtuanmanga** [Nicholas3388/LuaNode#11]
i bought a broad from this link
https://world.taobao.com/item/545443841643.htm?spm=a312a.7700714.0.0.M5KZlH#detail
and i flashed firmware from branch LuaNode_1.2.0 and blue and red led on broad work but when i open port in ESPlorer only Communication with MCU.. show and i can't upload code to ESP32
can you help me pls and sorry for my bad english

**Comment by Nicholas3388** [comment]
@anhtuanmanga Hi, please use the master branch. The latest sources are pushed to the master  branch. The other branches still have some problems.

**Comment by anhtuanmanga** [comment]
i tried with firmware from master branch too
here is my setup
![image](https://cloud.githubusercontent.com/assets/14345732/25468553/e9dae81c-2b40-11e7-9460-49501d2230ed.png)
but after finish flash only red led work
do i have to press any button when flash firmware?

**Comment by Nicholas3388** [comment]
@anhtuanmanga  The FLASH SIZE is 32Mbit

**Comment by anhtuanmanga** [comment]
still not work
do you have any document or guidline?

**Comment by Nicholas3388** [comment]
@anhtuanmanga Hi, we've published a book to introduce programming with ESP32, but it is wrote in Chinese. If you are not Chinese, I'm afraid you won't need it. 

For the firmware we provided in LuaNode, it will output some libs loaded information when power up. The following screenshot is the output info from my Macbook. [http://img1.ph.126.net/MDPdhBuNuTJoh7tqzS8AGg==/6632360791373571970.png](url)

Can you show me what's your output info when power up? You can see the output from ESPlorer, note that the baud rate is 115200.

**Comment by anhtuanmanga** [comment]
thank you for the help.
I have press RST button on ESPlorer, now the console show log like your screenshot.

**Comment by anhtuanmanga** [comment]
can you explaine for me about boot and en button

**Comment by Nicholas3388** [comment]
press en button will trigger hard reset. If you fail to connect to ESP32 device while using `flash_download_tools` to download firmware, press boot button will re-synchronize with ESP32.

**Comment by anhtuanmanga** [comment]
So they don't connect to GPIO1 and GPIO0?

**Comment by Nicholas3388** [comment]
The boot button connect to GPIO0, you can see that from the schematic. The schematic download link post on LuaNode github page
