### ISSUE TITLE
can not find rtc lib

### ISSUE THREAD

**Issue by WatorVapor** [Nicholas3388/LuaNode#3]
lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld: cannot find -lrtc

**Comment by Nicholas3388** [comment]
@WatorVapor  Hi, after cloned esp-idf from git, you will need to download some dependent libs. To do that, change directory to esp-idf and input 'git submodule update --init' on the terminal.

**Comment by WatorVapor** [comment]
thanks i will try it.

**Comment by WatorVapor** [comment]
It works good.
