### ISSUE TITLE
Powering ESP32 from VIN pin

### ISSUE THREAD

**Issue by ioios-io** [Nicholas3388/LuaNode#40]
MY board works perfectly when powered by USB, but when I put 5Vdc onto the VIN pin, the red led lights up but it doesn't boot (and peripherals powered on 3.3V don't receive power). I googled it and some say the 3.3V regulator needs more than 5v to function but I want to use the 5V power for other things too so I was relying on the 5V on VIN working.

I also noticed when I put 5V on VIN that the 3.3V pin also had 5V on it which seems wrong and damaging. Have I got some broken boards? (I have 3 and all three act the same).

The boards are just like the ESP32 board photos all over this repository.

Thanks!

**Comment by VictorLamoine** [comment]
The AMS117 regulator has a drop-out of approximately 1V (up to 1.3V http://www.advanced-monolithic.com/pdf/ds1117.pdf).

This means you need to supply at least 3.3 + 1 = 4.3V.
The board should start working with 4.3V (worst case 4.6 V) supplied on Vin.

You should not supply more than 12V on Vin, be careful of overheating!

Getting more than 3.3V on the 3V3 pin is not normal at all :smile:
